import os

ELASTICSEARCH_CLUSTER_NODES = os.environ.get("ELASTICSEARCH_CLUSTER_NODES")
KAFKA_BOOTSTRAP_ADDRESS = os.environ.get("KAFKA_BOOTSTRAP_ADDRESS")
KAFKA_SCHEMA_REGISTRY_URL = os.environ.get("KAFKA_SCHEMA_REGISTRY_URL")
