import os

print("1");
ELASTICSEARCH_CLUSTER_NODES = os.environ.get("ELASTICSEARCH_CLUSTER_NODES")
print(ELASTICSEARCH_CLUSTER_NODES)
KAFKA_BOOTSTRAP_ADDRESS = os.environ.get("KAFKA_BOOTSTRAP_ADDRESS")
print(KAFKA_BOOTSTRAP_ADDRESS)
KAFKA_SCHEMA_REGISTRY_URL = os.environ.get("KAFKA_SCHEMA_REGISTRY_URL")
print(KAFKA_SCHEMA_REGISTRY_URL)
